-- Space to setup configversion
-- configversion: 19ec5c7f9e83bc6534d657f6180feba2
conky.config = {
    out_to_wayland = true,
    alignment = 'middle_middle',
    own_window_argb_value = 0,
    own_window_type = 'desktop',
    default_shade_color = 'grey',
    draw_shades = true,
    font = 'Sxmo:size=13',
    use_xft = true,
    update_interval = 5,
}

conky.text = [[
${alignc}${font Sxmo:size=50:style=Bold}${time %H}${font Sxmo:size=50}:${time %M}${font}

${font Sxmo:size=20}${time %a %d %b %Y}${font}

${alignc}${font Sxmo:size=12}RAM ${mem} / ${memmax}
${alignc}Ядра ${execi 5 tr ',' '\n' < /sys/devices/system/cpu/online | awk -F- '{n+=($2==""?1:$2-$1+1)} END{print n}'}/${execi 3600 nproc --all}
${alignc}${execi 5 for c in 0 6; do f=/sys/devices/system/cpu/cpu$c/cpufreq/scaling_cur_freq; [ -r $f ] && printf '%d ' $(($(cat $f)/1000)); done} МГц${font}
]]
